services:
  db:
    image: mariadb:12
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'exit 0']
      interval: 5s
      timeout: 2s
      retries: 5

  wp:
    image: wordpress:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      JWT_SECRET: ${JWT_SECRET:-local_dev_secret_please_change}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_ENVIRONMENT_TYPE', 'local');
        define('STORESDK_JWT_ENABLED', true);
        define('STORESDK_JWT_SECRET', getenv('JWT_SECRET') ?: 'change_me');
    volumes:
      - wp_data:/var/www/html
      # Mount shared plugin implementation (single source of truth)
      - ./wp-plugin/store-sdk:/var/www/html/wp-content/plugins/store-sdk:ro

  wpcli:
    image: wordpress:cli
    depends_on:
      wp:
        condition: service_started
    user: '33:33' # www-data for proper file permissions
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:-wordpress}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE:-wordpress}
      - JWT_SECRET=${JWT_SECRET:-local_dev_secret_please_change}
      - WP_URL=${WP_URL:-http://localhost:8080}
      - WP_TITLE=${WP_TITLE:-Test Site}
      - WP_ADMIN_USER=${WP_ADMIN_USER:-admin}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD:-admin}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL:-admin@example.com}
      - TEST_CUSTOMER_USER=${TEST_CUSTOMER_USER:-customer}
      - TEST_CUSTOMER_PASSWORD=${TEST_CUSTOMER_PASSWORD:-customer123}
      - TEST_CUSTOMER_EMAIL=${TEST_CUSTOMER_EMAIL:-customer@example.com}
      - WC_STORE_ADDRESS=${WC_STORE_ADDRESS:-Syntagma Square}
      - WC_STORE_CITY=${WC_STORE_CITY:-Athens}
      - WC_STORE_COUNTRY=${WC_STORE_COUNTRY:-Greece}
      - WC_STORE_COUNTRY_CODE=${WC_STORE_COUNTRY_CODE:-GR}
      - WC_STORE_POSTCODE=${WC_STORE_POSTCODE:-10563}
      - WC_STORE_CURRENCY=${WC_STORE_CURRENCY:-EUR}
      - WC_STORE_SALES_TAX=${WC_STORE_SALES_TAX:-true}
      - WOO_COMMERCE_VERSION=${WOO_COMMERCE_VERSION:-}
      - WP_CLI_CACHE_DIR=/tmp/wp-cli-cache
    working_dir: /var/www/html
    volumes:
      - wp_data:/var/www/html
      - ./scripts:/scripts
      # Mount plugin implementation for wpcli
      - ./wp-plugin/store-sdk:/var/www/html/wp-content/plugins/store-sdk:ro
    entrypoint: ['bash', '/scripts/wp-entry.sh']

volumes:
  db_data:
  wp_data:
