name: ci

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

env:
  NODE_VERSION: 20
  # Ensure Nx prints useful logs in CI
  NX_VERBOSE_LOGGING: false
  # Avoid Nx daemon issues in ephemeral runners
  NX_DAEMON: false

jobs:
  setup-and-cache:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-nx.outputs.cache-primary-key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Need full history so Nx affected has a proper base commit
          fetch-depth: 0

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Cache Nx (previous runs)
        id: cache-nx
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-
            nx-${{ runner.os }}-

      - name: Print Nx Version / Projects
        run: |
          npx nx --version
          npx nx show projects

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup-and-cache
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-
            nx-${{ runner.os }}-
      - name: Run lint (all projects)
        run: |
          npx nx affected -t lint --parallel=3 --base=origin/main

  format:
    name: format
    runs-on: ubuntu-latest
    needs: setup-and-cache
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - name: Prettier Check (all)
        run: |
          npx prettier --version
          npx prettier --check .

  test:
    # DEPRECATED: unified test job replaced by granular jobs below
    if: false
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - run: echo "Replaced by test-unit, test-integration, and test-flow jobs."

  test-unit:
    name: tests / unit
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-
            nx-${{ runner.os }}-
      - name: Run Unit Tests (fast, no WP env)
        run: |
          npx nx test core -- src/lib/tests/unit
      - name: Upload Coverage to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          flags: unit
          fail_ci_if_error: false
          verbose: false
      - name: Upload Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: |
            coverage
            packages/**/coverage
          if-no-files-found: ignore

  test-integration:
    name: tests / integration
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-
            nx-${{ runner.os }}-
      - name: Start WordPress Environment
        env:
          WOO_COMMERCE_VERSION: ''
        run: |
          set -euo pipefail
          echo "Provisioning WordPress + WooCommerce for integration tests..."
          npm run wp:env:up
          npm run wp:cli:fast option get store_sdk_seeded || true
          npm run wp:cli:fast post list --post_type=product --posts_per_page=1 --format=json || true
      - name: Run Integration Tests
        run: |
          npx nx test core -- src/lib/tests/integration
      - name: Upload Coverage to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          flags: integration
          fail_ci_if_error: false
          verbose: false
      - name: Upload Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: |
            coverage
            packages/**/coverage
          if-no-files-found: ignore
      - name: Tear Down WordPress Environment
        if: always()
        run: npm run wp:env:down || true

  test-flow:
    name: tests / flow
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-
            nx-${{ runner.os }}-
      - name: Start WordPress Environment
        env:
          WOO_COMMERCE_VERSION: ''
        run: |
          set -euo pipefail
          echo "Provisioning WordPress + WooCommerce for flow tests..."
          npm run wp:env:up
          npm run wp:cli:fast option get store_sdk_seeded || true
      - name: Run Flow Tests
        run: |
          npx nx test core -- src/lib/tests/flow
      - name: Upload Coverage to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          flags: flow
          fail_ci_if_error: false
          verbose: false
      - name: Upload Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-flow
          path: |
            coverage
            packages/**/coverage
          if-no-files-found: ignore
      - name: Tear Down WordPress Environment
        if: always()
        run: npm run wp:env:down || true

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test-unit, test-integration, test-flow]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock') }}-
            nx-${{ runner.os }}-
      - name: build (all projects)
        run: |
          npx nx affected -t build --parallel=3 --base=origin/main
      - name: Package Size Summary (optional)
        if: always()
        run: |
          find packages -maxdepth 3 -type f -name package.json -printf "\n---- %p ----\n" -exec jq -r '.name + "@" + (.version // "0.0.0")' {} \;
