name: legacy-core-disabled

# Manual-only placeholder retained for history. Use ci.yml instead.
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy core workflow disabled. Use ci.yml for CI checks."
