name: post-merge

on:
  push:
    branches: [main]

permissions:
  contents: read

env:
  NODE_VERSION: 20
  NX_DAEMON: false

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - name: Lint
        run: npx nx affected -t lint --parallel=3 --base=origin/main
      - name: Test
        run: npx nx affected -t test --parallel=3 --base=origin/main
      - name: Build
        run: npx nx affected -t build --parallel=3 --base=origin/main
