name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # GITHUB_TOKEN : ${{ secrets.GH_TOKEN }}
      NPM_CONFIG_PROVENANCE: true
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npx nx build core

      - name: Publish
        run: |
          git config --global user.email "kostasmakris23@gmail.com"
          git config --global user.name "Kostas Makris"
          npx nx release -y
