name: WordPress.org Plugin Deploy
permissions:
  contents: read

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version to deploy'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate plugin
        run: npm run wp:plugin:validate

      - name: Build plugin package
        run: npm run wp:plugin:package

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WP_ORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}
          SLUG: store-sdk
          BUILD_DIR: plugins/store-sdk
          ASSETS_DIR: assets/wordpress-org

      - name: Upload plugin package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: store-sdk-plugin
          path: dist/wp-plugin/store-sdk.zip
          retention-days: 30
